/* Generated by MyraPad at 1/12/2023 9:09:28 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace BuildingGame.UI
{
	partial class MainMenu: Panel
	{
		private void BuildUI()
		{
			newLocalGame = new TextButton();
			newLocalGame.Text = "New Local Game";
			newLocalGame.Width = 200;
			newLocalGame.Height = 30;
			newLocalGame.BorderThickness = new Thickness(1);
			newLocalGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			newLocalGame.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			newLocalGame.Border = new SolidBrush("#FFFFFFFF");
			newLocalGame.Id = "newLocalGame";

			newMultiplayerGame = new TextButton();
			newMultiplayerGame.Text = "New Multiplayer Game";
			newMultiplayerGame.Width = 200;
			newMultiplayerGame.Height = 30;
			newMultiplayerGame.BorderThickness = new Thickness(1);
			newMultiplayerGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			newMultiplayerGame.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			newMultiplayerGame.Border = new SolidBrush("#FFFFFFFF");
			newMultiplayerGame.Id = "newMultiplayerGame";

			joinTo = new TextButton();
			joinTo.Text = "Join To...";
			joinTo.Width = 200;
			joinTo.Height = 30;
			joinTo.Margin = new Thickness(0, 10, 0, 0);
			joinTo.BorderThickness = new Thickness(1);
			joinTo.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			joinTo.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			joinTo.Border = new SolidBrush("#FFFFFFFF");
			joinTo.Id = "joinTo";

			joinToAddress = new TextBox();
			joinToAddress.Text = "127.0.0.1";
			joinToAddress.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			joinToAddress.Width = 200;
			joinToAddress.Margin = new Thickness(0, 5, 0, 0);
			joinToAddress.Id = "joinToAddress";

			playerName = new TextBox();
			playerName.Text = "player";
			playerName.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			playerName.Width = 200;
			playerName.Margin = new Thickness(0, 5, 0, 0);
			playerName.Id = "playerName";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Widgets.Add(newLocalGame);
			verticalStackPanel1.Widgets.Add(newMultiplayerGame);
			verticalStackPanel1.Widgets.Add(joinTo);
			verticalStackPanel1.Widgets.Add(joinToAddress);
			verticalStackPanel1.Widgets.Add(playerName);

			
			Background = new SolidBrush("#202020FF");
			Widgets.Add(verticalStackPanel1);
		}

		
		public TextButton newLocalGame;
		public TextButton newMultiplayerGame;
		public TextButton joinTo;
		public TextBox joinToAddress;
		public TextBox playerName;
	}
}
